# Base Python image
FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY workers/ ./workers/
COPY core/ ./core/

CMD ["python", "workers/main.py"]
