export { DashboardPage } from './Dashboard'
export { BucketsPage } from './Buckets'
export { FunctionsPage } from './Functions'
export { WorkflowsPage } from './Workflows'
export { EventRulesPage } from './EventRules'
export { IAMPage } from './IAM'
export { AuditLogsPage } from './AuditLogs'
